name: publish web
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        ftp-server: ${{ secrets.HOST }}
        ftp-username: ${{ secrets.USERNAME }}
        ftp-password: ${{ secrets.PASSWORD }}
